int Read(char *FileName,int MaxSize,char *Data);
int Delete(char *Filename);
int Write(char *FileName,int Size,char *Data);
int Format();
void List();
int Mkdir(char *Filename);
void Clean();
int login(char* uname, char* pwd);
void logout();
int Rmdir(char* dirName);
